version: "3.8"

services:
  go:
    build:
      dockerfile: ./infra/Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
